kamilkisiela/apollo-angular

- src/apolloQueryPipe.ts
- tests/apolloQueryPipe.ts
It allows to use `ApolloQueryPipe` with `@Apollo` and `Angular2Apollo.watchQuery()`.
```html
<ul>
<li *ngFor="let post of data | apolloQuery:'posts'">
{{ post.title }}
</li>
</ul>
```
> feat(ApolloQueryPipe): Support both results from decorator and service

- .github/PULL_REQUEST_TEMPLATE.md.md
- CHANGELOG.md
PR template is exactly the same as apollo-client's
Changelog has the same structure as other apollostack projects
> docs: Add change log and PR template

- CHANGELOG.md
- src/apolloDecorator.ts
Instead of passing just `mutation` and `variables`
> refactor(Apollo): pass all options to mutation

- CHANGELOG.md
- examples/hello-world/client/main.ts
- src/apolloDecorator.ts
- src/index.ts
Before:
```ts
class App {
data: any; // to avoid typescript errors
update(): void {
this.data.refetch();
}
}
```
After:
```ts
class App {
data: ApolloQuery; // contains refetch method
update(): void {
this.data.refetch();
}
}
```
We could also:
```ts
interface DataQuery extends ApolloQuery {
hero: Hero
}
class App {
data: DataQuery;
print(): void {
console.log(this.data.hero); // no error :)
}
update(): void {
this.data.refetch();
}
}
```
> ApolloQuery interface

- CHANGELOG.md
- package.json
- src/apolloDecorator.ts
- tests/apolloDecorator/queries.ts
- typings.json
Via https://github.com/apollostack/apollo-client/blob/master/CHANGELOG.md#v049:
> Add a new experimental feature to observable queries called `fetchMore`. It allows application developers to update the results of a query in the store by issuing new queries. We are currently testing this feature internally and we will document it once it is stable. [PR #472](https://github.com/apollostack/apollo-client/pull/472).
> Fetch more

- CHANGELOG.md
- examples/hello-world/client/imports/app.component.html
- examples/hello-world/client/imports/app.component.ts
- examples/hello-world/client/imports/app.module.ts
- global.d.ts
- package.json
- src/angular2Apollo.ts
- src/apolloQueryObservable.ts
- src/utils/observableQuery.ts
- src/utils/observeVariables.ts
- tests/_mocks.ts
- tests/angular2Apollo.ts
- tests/apolloQueryObservable.ts
- tests/index.ts
- tests/utils/index.ts
- tests/utils/observeVariables.ts
Closes #62
Example:
```ts
import { Subject } from 'rxjs/Subject';
const name = new Subject();
const city = new Subject();
const obs = client.watchQuery({
query, 
variables: {
name,
city
}
});
obs.subscribe(result => {
console.log(result);
});
// waits for values to be emitted
name.next('Kamil');
// still waits
city.next('Warsaw'); // build the query with { name: 'Kamil', city: 'Warsaw' }
city.next('Cracow'); // rebuild the query with { name: 'Kamil', city: 'Cracow' }
```
> Query's variables as Observables

- .npmignore
Currently `node_modules/angular2-apollo` is a garbage.
> chore: Add unnecessary things to npmignore

- CHANGELOG.md
- src/utils/ApolloHandle.ts
- tests/ApolloDecorator/queries.ts
> Refetch on new variables and fix the format of arguments in backcompat method

- CHANGELOG.md
- src/ApolloModule.ts
- src/ApolloQueryPipe.ts
- src/SelectPipe.ts
- src/index.ts
- tests/ApolloQueryPipe.ts
Also deprecate `ApolloQueryPipe`
---
Usage:
```html
<div *ngFor="let user of data | async | select: 'users'">{{ user.id }}</div>
```
Feels more natural than `apolloQuery: 'users'`.
---
@Urigo People can avoid using this pipe by simply using `map` operator but let's give them opportunity to choose between those options.
> SelectPipe

- package.json
Fixes for me issue #106, needed the chai typings file for `npm install` to run correctly.
> chore: include chai typings (#106)

- examples/hello-world/package.json
- examples/hello-world/src/typings.d.ts
- package.json
I was getting some errors of duplicate typings, and realized the problem had to do with graphql-typings, which is no longer needed, it seems.
> chore: typings fix for example

- tests/Angular2Apollo.spec.ts
- tests/ApolloModule.spec.ts
- tsconfig.json
> More tests

- CHANGELOG.md
- package.json
@Urigo I think we should publish it first as a Release Candidate because of this UMD thing and updated AoT compilation
> Release v0.9.0-rc.1

- package.json
No longer needed thanks to recent changes of apollo-client
> Remove types of node and isomorphic-fetch

- CHANGELOG.md
@Urigo I think, it would be good to deprecate `angular2-apollo`, so user would see a notice about it:
```
npm deprecate angular2-apollo "Use apollo-angular instead"
```
> Deprecate `angular2-apollo`

- CHANGELOG.md
- package.json
- src/tokens.ts
> Use `InjectionToken`, instead of deprecated `OpaqueToken`

- package.json
Clean was already run on prebuild and I've replaced prepublish with prepare to add support for installing via git as was introduced in npm5
From any project you can do: `npm i github:intellix/apollo-angular#npm5-scripts`
> chore(build): add support for npm5 git installation

- docs/source/basics/setup.md
Redirection to the correct link: ./basics/caching.html, because ./basics/cache.html not exists.
> Update cache docs link crashed

- packages/apollo-angular/tests/QueryRef.spec.ts
Tests for `setVariables` was an incorrect copy/paste from `setOptions`.
> test(core): setVariables is covered by tests

- docs/source/basics/queries.md
I was reading the Docs for queries and noticed a typo: Graph**i**QL -> GraphQL.
> Fixed typo in queries.md

- docs/package.json
- renovate.json
> Hoist Renovate config from nested `package.json` into root `renovate.json`.

- docs/README.md
In order to provide a more universal README.md across all documentation
deployment repositories, and most importantly, to reference the so-called
"documentation for the documentation".
> docs: Add/update documentation README.md.

- packages/apollo-angular/CHANGELOG.md
- packages/apollo-angular/package.json
Why TypeScript 2.8? I couldn't find an `Omit` type that would be compatible with 2.7 and 2.8+ versions. TS 2.8 brings `Exclude` type that is really helpful here. `Pick` + `Exclude` = `Omit`
Why we need `Omit` type?
In `Query` service we want to let user to use regular options (`WatchQueryOptions`) but without `query` and `variables` props because they both are defined already. Without `Omit` those properties would be required by TypeScript.
> build: change peerDependencies

- docs/source/index.md
Adds Ionic to the list of frameworks Apollo works great with (in Angular apps)
> Add Ionic to the list of supported frameworks in Angular

- docs/source/basics/setup.md
Using Angular Schematics I didn't get to set the link to the test server that you setup when creating your manual provider.
Also the loading didn't work because the boolean wasn't false to start with in the exchange-rates component.
> fixed loading and added test graphQL server

- docs/source/features/caching.md
I was using the Query service (https://www.apollographql.com/docs/angular/basics/services.html#Basic-example) as described in the article, and I figured out how to use it in the cache update. The query service seemed to be the way to go when you follow the guides in a linear fashion, so I wanted to share how to present the query in the proxy object.
> update cache when using Query service

- .github/PULL_REQUEST_TEMPLATE.md.md
Getting rid of this repos custom issue/PR templates (since we're no longer using Apollo Bot).
> Remove custom templates since we're disabling Apollo Bot

- docs/source/basics/local-state.md
- docs/source/basics/setup.md
By switching over to an arrow function AOT compilation works properly. In addition, the documentation should show it this way since it's typically the way providers are listed.
> docs: use arrow function in useFactory

- packages/apollo-angular-link-http-common/src/utils.ts
Fixes issue #1096 
Angular CLI was removing code when running production optimisations.  I don't have a satisfactory explanation into why other than simply a bug hidden somewhere in Angular CLI / Webpack / Uglify.  This code change seems to trick it into knowing that the code is necessary.
> Bugfix for Issue #1096

- docs/source/basics/queries.md
`returnPartialData` has been [removed in Apollo 1.0](https://gist.github.com/helfer/3bbd1a727e30bbad9d2873803855fb91#returnpartialdata). This change removes information about that parameter from Queries docs to avoid potential confusion.
> docs: remove information about returnPartialData query option

- docs/source/recipes/boost-migration.md
The explanation on how to migrate the `clientState` object was confusing. At first I thought I was meant to pass the object `apollo-link-state` as a propriety. Like:
```ts
{
cache: new InMemoryCache(),
link: ApolloLink.from([
...
]),
clientState: {
resolvers,
typeDefs
}
}
```
I rephrased it to make it more clear.
> Clarifications in boost-migration.md

- packages/apollo-angular-link-http-common/package.json
- packages/apollo-angular-link-http/package.json
Since the http package is deprecated, there is no need to have it in dependencies, also it causes a warn when installing the package:
```
npm WARN apollo-angular-link-http@1.6.0 requires a peer of @angular/core@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-angular-link-http@1.6.0 requires a peer of @angular/common@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-angular-link-http-common@1.6.0 requires a peer of @angular/core@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-angular-link-http-common@1.6.0 requires a peer of @angular/common@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
```
Remove …
> chore(deps): remove @angular/http dependency

- docs/source/index.mdx
Fix broken Markdown link formatting in the Getting Started docs.
> Fix broken link in Getting Started docs

- docs/source/basics/caching.md
The apollo-angular docs still use cacheResolves to refer to cacheRedirects. From apollographql/apollo-client#4971.
> Update reference to cacheRedirects in docs

- docs/source/recipes/authentication.md
`apollo: Apollo` should be injected via constructor and not just a simple declaration
> docs(authentication.md): apollo should be injected via constructor in AuthService

- packages/apollo-angular/CHANGELOG.md
- packages/apollo-angular/src/Apollo.ts
According to apollo-client it returns a FetchResult<T> whereas apollo-angular says it's an any: https://github.com/apollographql/apollo-client/blob/7eaf4132cd2cd6244260777799406aaa03fcf377/packages/apollo-client/src/ApolloClient.ts#L355
> Fixed type definition for subscribe

- packages/apollo-angular-boost/CHANGELOG.md
- packages/apollo-angular-boost/package.json
- packages/apollo-angular/CHANGELOG.md
- packages/apollo-angular/package.json
- Fixed type definition for subscribe [PR #1290](https://github.com/apollographql/apollo-angular/pull/1290)
- Fix global scope naming for UMD build [PR #1305](https://github.com/apollographql/apollo-angular/pull/1305)
- Introduce useInitialLoading in watch [PR #1306](https://github.com/apollographql/apollo-angular/pull/1306)
> Release v1.7.0

- docs/source/recipes/pagination.md
`forceFetch` has been replaced with `fetchPolicy: 'network-only'` since ApolloClient 1.0:
https://s3.amazonaws.com/apollo-docs-1.x/migration.html#fetchPolicy
> Correct outdated `forceFetch` in `apollo-angular` pagination recipe

- packages/apollo-angular/testing/src/operation.ts
- packages/apollo-angular/testing/tests/operation.spec.ts
closes #1469 
plus, some refactoring for tests
I'm not sure about changelogs. Shall I do it manually?
> feat(apollo-angular): Adds flushData method to TestingOperation

- website/docs/development-and-testing/testing.md
`Testbed.get` has been [deprecated](https://angular.io/api/core/testing/TestBed#get) since Angular 9.0
> Replace `get` with `inject`

- packages/apollo-angular/src/query-ref.ts
- packages/apollo-angular/tests/QueryRef.spec.ts
currentResult was removed in Apollo v3 and replaced by getCurrentResult. In apollo-angular v1, currentResult() method was exposed.
This pull request is to expose the getCurrentResult method in QueryRef.
> Issue 1580 - expose get current result

- website/docs/data/subscriptions.md
Without appending the `graphql` path, I get the following error connecting to `apollo-server-express@2.18.2`:
```
WebSocket connection to 'ws://localhost:5000/' failed: Error during WebSocket handshake: Unexpected response code: 400
```
> Correct WebSocketLink URI in Subscriptions docs

- packages/apollo-angular/CHANGELOG.md
- packages/apollo-angular/src/apollo.ts
Source: https://stackoverflow.com/questions/39044803/syntaxerror-missing-in-const-declaration-firefox-50
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1101653
In my case build breaks in firefox 52, this is the medcine.
> Fix: Use let in Apollo constructor due to firefox bug

- website/docs/recipes/webpack.md
- Updated Webpack configuration: Use "rules" instead of "loaders"
- Short explanation how to apply a Webpack configuration when using Angular CLI
> Update webpack.md: configuration example

- website/src/css/custom.css
This PR is to fix the overlap between bottom menu button and chat button as seen in the screenshot for mobile devices.
> Fixed the overlapping menu button in mobile devices

- website/docs/performance/server-side-rendering.md
This fixed a browser console error when executing the SSR example from the docs:
`BrowserTransferStateModule` is imported in the app module, but not included in the imports array.
Not sure if this is worth an entry in the the changelog?
- [ x ] If this PR is a new feature, please reference a discussion where a consensus about the design was reached (not necessary for small changes)
- [ x ] Make sure all of the significant new logic is covered by tests
- [ x ] Try to include the Pull Request inside of CHANGELOG.md
> Fix "NullInjectorError: No provider for TransferState!" for ssr example

- packages/apollo-angular/CHANGELOG.md
- packages/apollo-angular/package.json
This also drops older Angular versions that are not officially
supported anymore according to:
https://angular.io/guide/releases#support-policy-and-schedule
And it also align other dependencies that still allowed obsoletes
versions.
Fixes #1669
> Declare Angular 12 support

- packages/apollo-angular/CHANGELOG.md
- packages/apollo-angular/src/apollo.ts
- packages/apollo-angular/tests/Apollo.spec.ts
I was following the documentation about [multiple clients](https://www.the-guild.dev/graphql/apollo-angular/docs/recipes/multiple-clients#creating-clients-using-apollo_named_options), I encountered an error stating `Client has not been defined yet`.
The documentation states that if you have a named option `default`, it will be the default client. That does not work.
Currently, if you provide options for a `default` client through `APOLLO_NAMED_OPTIONS`, it creates a "named client" named `default`. Accessing it is not possible because the actual default client is not set, and using `use('default')` results in the default client.
This fixes that. The test added fails without the fix.
> fix: create default client if named client is named default

- .github/dependabot.yml
Because we regularly update our deps manually, we want to be notified of only security issues and major versions
> Reduce Dependabot noise

- .changeset/gorgeous-coats-shave.md
- package.json
- packages/apollo-angular/src/apollo.ts
- packages/apollo-angular/src/query-ref.ts
- packages/apollo-angular/src/query.ts
- packages/apollo-angular/src/types.ts
- yarn.lock
to accommodate an upstream type change in @apollo/client@3.7.6
This addresses https://github.com/kamilkisiela/apollo-angular/issues/1907
> let TVariable generics extend OperationVariables

- .changeset/big-bears-roll.md
- .github/workflows/main.yml
- package.json
- packages/apollo-angular/headers/ng-package.json
- packages/apollo-angular/http/ng-package.json
- packages/apollo-angular/http/tests/__snapshots__/ssr.spec.ts.snap
- packages/apollo-angular/http/tests/ssr.spec.ts
- packages/apollo-angular/jest.config.js
- packages/apollo-angular/ng-package.json
- packages/apollo-angular/package.json
- packages/apollo-angular/persisted-queries/ng-package.json
- packages/apollo-angular/schematics/tsconfig.json
- packages/apollo-angular/testing/ng-package.json
- packages/apollo-angular/tsconfig.test.json
- packages/demo/angular.json
- packages/demo/tsconfig.app.json
- packages/demo/tsconfig.json
- tsconfig.json
- yarn.lock
* Removed a test case that was deprecated and is now removed for Angular 16
* Pulled minimum node version to 16 as it is now required by angular
* Updated ng-packagr to a version that supports v16, updated schema references as they were outdated
> feat: Update to Angular 16

- .changeset/unlucky-falcons-breathe.md
- packages/apollo-angular/testing/src/module.ts
closes https://github.com/kamilkisiela/apollo-angular/issues/2072
> Disable dev-tool check when using ApolloTestingModule

- website/src/pages/docs/development-and-testing/testing.mdx
If fragments are used the mock data needs to specify the `__typename`. Otherwise the received object is empty.
See this discussion: https://github.com/kamilkisiela/apollo-angular/issues/1624
> Mentioned __typename in mock data

- website/src/pages/docs/performance/server-side-rendering.mdx
Adds information about the Apollo client development tools that can cause SSR to hang.
investigation stemming from [this comment on this issue](https://github.com/kamilkisiela/apollo-angular/issues/1698#issuecomment-1999620273)
> include information about connectToDevTools

- .changeset/chilly-spiders-protect.md
- packages/apollo-angular/http/src/http-batch-link.ts
- packages/apollo-angular/http/src/http-link.ts
- packages/apollo-angular/http/src/utils.ts
- packages/apollo-angular/persisted-queries/src/index.ts
- packages/apollo-angular/persisted-queries/tests/persisted-queries.spec.ts
- packages/apollo-angular/schematics/install/index.ts
- packages/apollo-angular/schematics/install/schema.ts
- packages/apollo-angular/schematics/tests/ng-add.spec.ts
- packages/apollo-angular/schematics/utils/ast.ts
- packages/apollo-angular/src/apollo.ts
- packages/apollo-angular/src/mutation.ts
- packages/apollo-angular/src/query-ref.ts
- packages/apollo-angular/src/query.ts
- packages/apollo-angular/src/subscription.ts
- packages/apollo-angular/src/types.ts
- packages/apollo-angular/src/utils.ts
- packages/apollo-angular/testing/tests/operation.spec.ts
- packages/apollo-angular/tests/Apollo.spec.ts
- tsconfig.json
- `ApolloBase.client` throws an error if no client has been created
beforehand. The behavior now matches the typing that always declared a
client existed. In most cases, you should pass either `apolloOptions`
or `apolloNamedOptions` to `Apollo.constructor` to create the
client immediately upon construction.
- `ApolloBase.query()`, `ApolloBase.mutate()` and
`ApolloBase.subscribe()` all have a new constraint on `V`. If you
inherit from this class, you might need to adjust your typing.
- Classes that inherit `Query`, `Mutation` and `Subscription` must
declare the `document` member. This requirement always existed at
runtime but was not enforced at compile time until now. If you
generated code, you have nothing to do.
- `QueryRef.getLastResult()` and `QueryRef.getLastError()` might return …
> Use Typescript strict mode

- .changeset/dirty-pigs-suffer.md
- packages/apollo-angular/README.md
- packages/apollo-angular/http/src/http-batch-link.ts
- packages/apollo-angular/http/src/http-link.ts
- packages/apollo-angular/http/tests/ssr.spec.ts
- packages/apollo-angular/src/apollo.ts
- packages/apollo-angular/src/mutation.ts
- packages/apollo-angular/src/query-ref.ts
- packages/apollo-angular/src/query.ts
- packages/apollo-angular/src/subscription.ts
- packages/apollo-angular/src/utils.ts
- packages/apollo-angular/testing/src/operation.ts
- packages/apollo-angular/tests/Apollo.spec.ts
- packages/demo/src/app/pages/author/author-page.component.ts
- packages/demo/src/app/pages/posts/posts-page.component.ts
- packages/demo/src/app/pages/posts/upvoter.component.ts
- scripts/prepare-e2e.js
- website/src/pages/docs/caching/advanced-topics.mdx
- website/src/pages/docs/data/error-handling.mdx
- website/src/pages/docs/data/mutations.mdx
- website/src/pages/docs/data/queries.mdx
- website/src/pages/docs/data/services.mdx
- website/src/pages/docs/development-and-testing/testing.mdx
- website/src/pages/docs/get-started.mdx
- website/src/pages/docs/local-state/managing-state-with-field-policies.mdx
- website/src/pages/docs/performance/improving-performance.mdx
- website/src/pages/docs/performance/server-side-rendering.mdx
- website/src/pages/docs/recipes/authentication.mdx
Otherwise, we might encounter a delay of 10 seconds, and this might lead to suboptimal experience as described in https://angular.io/errors/NG0506
Fixes #2251
> ApolloClient does not delay the application becoming stable

- website/src/pages/docs/data/subscriptions.mdx
Reference to issue #1801
In the documentation, replace the deprecated `subscriptions-transport-ws` with `graphql-ws`.
Moreover, in `getMainDefinition`, first check `kind`, then `operation`, to avoid both runtime errors and _TypeScript_ errors.
> docs: graphql-ws instead of deprecated subscriptions-transport-ws

- renovate.json
Because it generates a ton of noises to merge PR, but it brings little value for this specific project.
And because `automerge` could reduce the noise, but it then merges broken builds as seen in https://github.com/kamilkisiela/apollo-angular/pull/2267, which is a huge no-go.
And because I don't have time, nor interest, to figure out a better configuration than that.
> Disable Renovate entirely

- .changeset/red-foxes-listen.md
- packages/apollo-angular/src/apollo.ts
Version 7.1.1 introduces a import from @apollo/client, that causes typescript to need a reference from React. It needs to be an import from @apollo/client/core, like all the other imports.
- [ x ] If this PR is a new feature, please reference a discussion where a consensus about the design
- [ x ] Make sure all the significant new logic is covered by tests
> Use import from @apollo/client/core instead of @apollo/client

- .changeset/nine-knives-lie.md
- .prettierignore
- packages/apollo-angular/http/src/http-link.ts
- packages/apollo-angular/http/src/types.ts
- packages/apollo-angular/http/src/utils.ts
- packages/demo/src/app/pages/author/author-page.component.ts
- packages/demo/src/app/pages/posts/posts-page.component.ts
- packages/demo/src/app/pages/posts/upvoter.component.ts
- packages/demo/tsconfig.json
- website/src/pages/docs/data/network.mdx
> Relax type to be able to use `extract-files` properly

- .changeset/dirty-seals-heal.md
- packages/apollo-angular/src/gql.ts
Casting, instead of wrapping, the existing `gql` function, save ~60 bytes, and avoid an extra function call at runtime
> Smaller bundle for `gql`

- .changeset/nine-pets-wait.md
- packages/apollo-angular/src/gql.ts
- website/src/pages/docs/get-started.mdx
Because importing the same thing from two different import points will increase the final bundle size. If you want a different name for the tag function, then use `as` syntax, such as:
```ts
import {gql as graphql} from 'apollo-angular';
```
> Deprecate `graphql` alias for `gql` tag function

- .changeset/apollo-angular-2333-dependencies.md
- .changeset/beige-seals-allow.md
- .github/workflows/main.yml
- packages/apollo-angular/package.json
> Requires @apollo/client ^3.10.0 for watchFragment

- .changeset/sweet-pigs-fix.md
- packages/apollo-angular/schematics/install/files/module/graphql.module.ts
- packages/apollo-angular/src/apollo-module.ts
- packages/apollo-angular/src/gql.ts
- packages/apollo-angular/src/index.ts
- packages/apollo-angular/testing/src/module.ts
- packages/apollo-angular/tests/index.spec.ts
- scripts/prepare-e2e.js
Instead of `ApolloModule`, use either `provideApollo()` or `provideNamedApollo()`.
Instead of `import {graphql} from 'apollo-angular';` use `import {gql as graphql} from 'apollo-angular';`
> Drop deprecated things

- .changeset/stale-penguins-remember.md
- packages/apollo-angular/testing/src/operation.ts
According to https://github.com/apollographql/apollo-client/pull/11789
> `FormattedExecutionResult` instead of `ExecutionResult`

- .changeset/thin-otters-move.md
- packages/apollo-angular/src/query-ref.ts
- packages/apollo-angular/tests/Apollo.spec.ts
- packages/apollo-angular/tests/QueryRef.spec.ts
Tests are changed because the `ObservableQuery` methods must be mocked or spied on before constructing a `QueryRef`. Because the `QueryRef` will immediately bind the `ObservableQuery` methods internally.
Fixes #2346 (again)
> Let types flow naturally from `ObservableQuery`
