examples/hello-world/client/main.html, examples/hello-world/client/main.ts, examples/hello-world/imports/api/schema.js, examples/hello-world/package.json, examples/hello-world/server/main.js
=> refactor(hello-world): working example

examples/hello-world/imports/api/schema.js
=> reactor(hello-world): server-side support for mutation

package.json
Same thing as in `angular-meteor` which is a commit message validation using angular.js guidelines.
=> chore: commit message checking

src/apolloDecorator.ts, tests/apolloDecorator/queries.ts
Because we had variables outside an instance of component...
=> fix(Apollo): missing data in reused component

package.json, tests/_helpers.ts, tests/apolloDecorator/queries.ts
=> chore: use graphql-tag package

LICENSE, package.json
just like in any other apollostack repository
=> chore: Add MIT license

CHANGELOG.md, examples/hello-world/tsconfig.json, package.json, src/angular2Apollo.ts, src/apolloQueryObservable.ts, tests/angular2Apollo.ts, tests/apolloQueryObservable.ts, tests/index.ts
=> feat(Angular2Apollo): support for Rx.Observable

CHANGELOG.md, examples/hello-world/client/main.html, src/apolloDecorator.ts
Related #36 and apollostack/apollo-client#342
=> Loading state of a query

CHANGELOG.md, src/apolloQueryObservable.ts, tests/apolloQueryObservable.ts
=> fix(ApolloQueryObservable): Make it compatible with Rx.Observable

CHANGELOG.md, src/utils/ApolloHandle.ts
=> feat(ApolloQuery): add missing fetchMore method

package.json, tests/Angular2Apollo.ts
Closes #122 but "partially" (funny or not but it's a joke)
=> Fixes build failing by using returnPartialData when do refetch

CHANGELOG.md, src/Angular2Apollo.ts
WatchQueryOptions as options and Promise as result
=> feat(Angular2Apollo): Add more types

CHANGELOG.md, package.json, src/Angular2Apollo.ts, tsconfig.json, yarn.lock
=> Use exposed types of options for each method of Angular2Apollo

package.json
=> chore(package): update tslint to version 4.2.0

src/Angular2Apollo.ts, tests/Angular2Apollo.spec.ts
=> feat(Angular2Apollo): expose instance of ApolloClient

examples/hello-world/package.json, examples/hello-world/src/app/app.component.ts, package.json, rollup.config.js, src/Angular2Apollo.ts, tests/ApolloModule.spec.ts, tests/_mocks.ts, yarn.lock
=> Tree-shaking with apollo-client and apollo-client-rxjs

package.json, tests/_mocks.ts
Related apollostack/apollo-client#1170
=> chore: fix paths of apollo-client modules

CHANGELOG.md, package.json
I merged logs of every RC into just one, single list
=> Release v0.9.0

.travis.yml, README.md, examples/hello-world/package.json, examples/hello-world/src/app/app.component.ts, examples/hello-world/src/app/app.module.ts, examples/hello-world/yarn.lock, package.json
and release 0.9.1
#JustAngular
=> chore(rename): Rename angular2-apollo to apollo-angular 

examples/hello-world/README.md
=> docs(example): remove the joke on how to run

packages/apollo-angular-link-http/CHANGELOG.md, packages/apollo-angular-link-http/src/HttpLink.ts, packages/apollo-angular-link-http/tests/HttpLink.spec.ts
=> fix(link-http): stringify variables when using GET

packages/apollo-angular-link-http/src/HttpLink.ts, packages/apollo-angular-link-http/src/utils.ts
Fix: https://github.com/apollographql/apollo-angular/issues/404
=> fix(link-http): remove url normalization

packages/apollo-angular-link-http/CHANGELOG.md, packages/apollo-angular-link-http/src/HttpLink.ts
Many browsers does not support it
Fixes #407
=> fix(link-http): Replace Array.includes with Array.indexOf

packages/apollo-angular/src/Apollo.ts, packages/apollo-angular/src/api.ts
This PR addresses this issue https://github.com/apollographql/apollo-angular/issues/470
=> feat(api): expose apollobase

packages/apollo-angular-link-http/CHANGELOG.md, packages/apollo-angular-link-http/package.json
=> feat(link-http): support graphql@0.12.3

docs/source/recipes/pagination.md
The link was missing a closing )
=> fix pagination fetchMore link

docs/source/basics/mutations.md
Hi, great library I'm liking it and GraphQL a lot so far. Here are some small grammar fixes to the documentation that I found. Keep up the great work, and I'm glad to be contributing what I can back to the project.
=> Fixed grammar in docs/source/basics/mutations.md

docs/source/basics/queries.md
Some of these changes are straightforward (better English style and grammar).
I'm also suggesting two more substantial changes:
* I tried to clarify the difference between `watchQuery` and `query`. When I first read the documentation, I was confused as to why `watchQuery` "passes multiple results."
* As far as I can tell, several pieces of the sample code don't [unsubscribe from or cancel](https://stackoverflow.com/q/38008334/25507) subscriptions, so the queries stay active even when the component is removed. This seems like a bug, so I've updated the example code to fix this.
I haven't been using Apollo Client very long, so if my changes are incorrect, or if I've misunderstood something, please let me know.
=> Update query documentation

packages/apollo-angular-link-http-batch/CHANGELOG.md, packages/apollo-angular-link-http-batch/package.json, packages/apollo-angular-link-http/CHANGELOG.md, packages/apollo-angular-link-http/package.json
```
apollo-angular-link-http@1.0.3
apollo-angular-link-http-batch@1.0.1
```
=> Release http v1.0.3 and http-batch v1.0.1

docs/source/basics/setup.md, packages/apollo-angular/src/Apollo.ts, packages/apollo-angular/src/api.ts, packages/apollo-angular/src/tokens.ts, packages/apollo-angular/tests/integration.spec.ts
=> Create Apollo on the Dependency Injection level

packages/apollo-angular-cache-ngrx/CHANGELOG.md, packages/apollo-angular-link-headers/CHANGELOG.md, packages/apollo-angular-link-http-batch/CHANGELOG.md, packages/apollo-angular-link-http-common/CHANGELOG.md, packages/apollo-angular-link-http/CHANGELOG.md, packages/apollo-angular-link-persisted/CHANGELOG.md, packages/apollo-angular/CHANGELOG.md
=> Changelog updates, prepping for deploy

docs/source/recipes/authentication.md
This shows an example of using a promise inside of the setContext function, when waiting for a refreshed token.
I have used the example of the adal.js library as that's what I have experience with.
=> Example of an observable/promise in setContext()

docs/source/features/cache-updates.md
fixes #715 
- also updated code snippets for current api
Used language from the [react Apollo Client docs](https://www.apollographql.com/docs/react/advanced/caching.html#cacheRedirect)
=> fix(docs): corrected cacheResolver -> cacheRedirect

docs/source/migration.md
Fixes #521.
I'm not sure if this is a complete solution, the comment [here](https://github.com/apollographql/apollo-angular/issues/425#issuecomment-346943066) mentions combineLatest but I'm not sure where that's needed.
=> docs(migration): Observable variables not supported

docs/_config.yml, docs/source/basics/services.md, docs/source/guides/tools-and-packages.md
=> docs: community packages and tools

docs/source/basics/setup.md
=> docs(setup): info about esnext.asynciterable

docs/source/guides/testing.md
Fixes broken code in testing docs and resolves #796
=> docs(testing): fix broken code in testing doc 

docs/source/basics/setup.md
I'm just starting with this, but thought I could contribute with something.
Found two h2#installation, and that's a no no I'm my view.
=> Fix repeated headings

packages/apollo-angular-link-persisted/CHANGELOG.md, packages/apollo-angular-link-persisted/package.json, packages/apollo-angular-link-persisted/src/index.ts, packages/apollo-angular-link-persisted/tests/index.spec.ts
=> feat(persisted): useGETForHashedQueries

packages/apollo-angular-link-http-batch/CHANGELOG.md, packages/apollo-angular-link-http-batch/package.json, packages/apollo-angular-link-http-common/CHANGELOG.md, packages/apollo-angular-link-http-common/package.json, packages/apollo-angular-link-http/CHANGELOG.md, packages/apollo-angular-link-http/package.json
=> feat(http): support GraphQL v14

docs/source/basics/services.md
I missed an example with the typing for the extended Query. This confused me a bit so I hope it is clearer now for other grasshoppers.
=> added typing for Response in Query class

docs/source/index.md
=> Nothing Is Broken

packages/apollo-angular/CHANGELOG.md, packages/apollo-angular/src/Apollo.ts, packages/apollo-angular/src/Mutation.ts, packages/apollo-angular/src/Query.ts, packages/apollo-angular/src/QueryRef.ts, packages/apollo-angular/src/Subscription.ts, packages/apollo-angular/src/types.ts
```
apollo-angular@1.5.0-alpha.a7af3a5
```
=> feat(core): more strict

docs/source/basics/mutations.md
I am not sure how to include the pull request inside the CHANGELOG.md, some guidance if required would be awesome.
I encountered a small error in the documentation, saw that there was [an open pull request](https://github.com/apollographql/apollo-angular/pull/554) for it but the author wouldn't sign the CLA. So here a pull request solving the same issue.
=> [DOC] Basics Mutation: Removed subscribe from service

docs/source/features/fragments.md
=> Address example typo

docs/source/basics/services.md
=> make the link work

docs/source/basics/local-state.md, docs/source/basics/setup.md, docs/source/recipes/boost-migration.md, packages/apollo-angular-boost/README.md
Port launchpad examples over to codesandbox and update the links.
=> Launchpad -> Codesandbox

package.json, packages/apollo-angular-boost/package.json, packages/apollo-angular-cache-ngrx/package.json, packages/apollo-angular-link-headers/package.json, packages/apollo-angular-link-http-batch/package.json, packages/apollo-angular-link-http-common/package.json, packages/apollo-angular-link-http/package.json, packages/apollo-angular-link-persisted/package.json, packages/apollo-angular/package.json, packages/apollo-angular/schematics/utils/ast.ts
=> Update to TypeScript v3.2 and @schematics/angular v7.2.2

docs/source/basics/local-state.md, docs/source/guides/state-management.md
This MR updates the local state documentation to align with Apollo version 2.5. It is heavily inspired by the [react documentation](https://www.apollographql.com/docs/react/essentials/local-state). Feedback is welcome!
* #1119
=> docs(): update local state documentation to align with v2.5

docs/source/features/developer-tooling.md
Just a real small change that doesn't require tests.
=> Just adding a space between words

docs/source/api/apollo-client.md
Resolves #1129 
I'm not sure how the documentation works for the website, but I copied the API from the React documentation (Apollo-Client) and put it into Apollo-Angular.
=> added api for client

docs/source/features/caching.md
=> Fix typo in markdown for URL

packages/apollo-angular/src/QueryRef.ts
=> Fixed type definition for SubscribeToMoreOptions

packages/apollo-angular/src/Apollo.ts, packages/apollo-angular/src/QueryRef.ts, packages/apollo-angular/tests/Apollo.spec.ts
=> Allow to remove a client from registry

docs/source/recipes/authentication.md
Present code example throws totally unclear error, as described in https://github.com/apollographql/apollo-angular/issues/1160
=> Update Authorization header example

docs/source/index.mdx
=> Fix broken links to setup

docs/source/features/developer-tooling.md
=> Fix typo in developer-tooling docs

docs/source/basics/queries.md
Added missing import statements
=> Added missing import statements

docs/source/features/developer-tooling.md
=> Fix typo in Typescript and Flow --addTypename

docs/source/guides/testing.md, packages/apollo-angular/CHANGELOG.md, packages/apollo-angular/src/Apollo.ts, packages/apollo-angular/src/index.ts, packages/apollo-angular/src/tokens.ts, packages/apollo-angular/src/types.ts, packages/apollo-angular/testing/src/backend.ts, packages/apollo-angular/testing/src/controller.ts, packages/apollo-angular/testing/src/index.ts, packages/apollo-angular/testing/src/module.ts, packages/apollo-angular/testing/src/operation.ts, packages/apollo-angular/testing/tests/operation.spec.ts
=> Introduce APOLLO_NAMED_OPTIONS and named clients in testing utils

packages/apollo-angular/CHANGELOG.md, packages/apollo-angular/src/Apollo.ts
=> Use private method instead of get accessor to access ApolloClient

docs/source/features/error-handling.md
=> Fixes very minor typo

docs/source/recipes/authentication.md
For me it was a bit confusing that the import was not provided. Given the amount of apollo packages it really is necessary to make it clear.
=> [documentation] Added missing setContext import in authentication section

CONTRIBUTING.md
I never worked with Lerna before and found it a bit difficult to figure out all bits and pieces. 
I added bootstrap command into the doc to help newcomers.
=> docs: how to setup development environment

docs/source/features/error-handling.md
=> Small typo in the docs

packages/apollo-angular/schematics/migrations/v2.ts, packages/apollo-angular/schematics/tests/migration-v2.spec.ts, packages/apollo-angular/schematics/tests/ng-add.spec.ts, packages/apollo-angular/schematics/tests/utils.spec.ts, packages/apollo-angular/schematics/utils/file.ts
Supports comments in JSON
Related #1548
=> Parse JSON with TypeScript

packages/apollo-angular-link-persisted/src/index.ts
=> Update the imports for ApolloLink and setContext

website/docs/development-and-testing/testing.md
This is only a minor fix of the documentation.
=> Add missing "let" statements

website/docs/migration.md
I'm not sure were these repetitions intentional, but it looks like a bug for me. I suggest replacing it with a double exclamation emoji
=> docs: Migriaton guide changes

packages/apollo-angular/CHANGELOG.md, packages/apollo-angular/http/src/http-batch-link.ts, packages/apollo-angular/http/src/http-link.ts, packages/apollo-angular/http/src/utils.ts, packages/apollo-angular/http/tests/http-batch-link.spec.ts, packages/apollo-angular/http/tests/http-link.spec.ts
=> Support clientAwareness in Http links

jest.config.js, packages/apollo-angular/CHANGELOG.md, packages/apollo-angular/testing/src/operation.ts, packages/apollo-angular/testing/tests/module.spec.ts
=> fix: test data modification

packages/apollo-angular/README.md
=> Update README.md with angular/ac versions

.github/workflows/main.yml
Changes to run required checks fo PRs as well
=> CI changes for PRs

packages/apollo-angular/package.json
Added Angular 11.0.0 peer dependency to address issue #1609
=> Added Angular 11 peer dependency

packages/apollo-angular/CHANGELOG.md, packages/apollo-angular/http/src/http-batch-link.ts, packages/apollo-angular/http/src/http-link.ts, packages/apollo-angular/http/src/types.ts, packages/apollo-angular/http/tests/http-batch-link.spec.ts, packages/apollo-angular/http/tests/http-link.spec.ts
Continuation of https://github.com/kamilkisiela/apollo-angular/pull/1630#issuecomment-788797221
Fixes #1630
=> Introduce `operationPrinter` to `HttpLink` and `HttpBatchLink`

website/docs/development-and-testing/testing.md
=> Add documentation about testing mutation

packages/apollo-angular/README.md
The link that points to the queries documentation was invalid.
=> (docs) fix a broken link

packages/apollo-angular/CHANGELOG.md, packages/apollo-angular/http/src/http-link.ts, packages/apollo-angular/http/src/types.ts, packages/apollo-angular/http/tests/http-link.spec.ts, website/docs/data/network.md
=> Introduce useGETForQueries in HttpLink

.github/ISSUE_TEMPLATE/bug_report.md
Nothing extraordinary, I just figured that some people might prefer to have an automated way to gather the relevant versions.
=> Bug Report Issue Template: Instructions to autogenerate environment

.github/workflows/website.yml, algolia/config.json, website/docusaurus.config.js, website/package.json, website/patches/@docsearch+react+3.0.0-alpha.34.patch, website/patches/@docusaurus+theme-search-algolia+2.0.0-alpha.72.patch
Added support for multi-site search with algolia
@kamilkisiela You may want to add `ALGOLIA_API_KEY` and `ALGOLIA_APPLICATION_ID` to the secrets as other repos for the workflow to work.
=> Added support for multi-site search with algolia

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, packages/apollo-angular/README.md, packages/apollo-angular/http/src/http-batch-link.ts, packages/apollo-angular/http/src/http-link.ts, packages/apollo-angular/http/src/utils.ts, packages/apollo-angular/http/tests/http-batch-link.spec.ts, packages/apollo-angular/http/tests/http-link.spec.ts, packages/apollo-angular/schematics/install/index.ts, packages/apollo-angular/src/apollo.ts, packages/apollo-angular/testing/src/backend.ts, packages/apollo-angular/tests/integration.spec.ts, scripts/bump.js, website/src/components/index-page.tsx, website/src/pages/docs/data/fragments.mdx, website/src/pages/v1/basics/local-state.mdx, website/src/pages/v1/basics/network-layer.mdx, website/src/pages/v1/features/fragments.mdx, website/src/pages/v1/features/static-typing.mdx, website/src/pages/v1/migration.mdx, website/src/pages/v2/performance/server-side-rendering.mdx
=> Fix various minor typos

.github/workflows/main.yml, packages/apollo-angular/package.json
=> Angular 15

website/src/pages/docs/index.mdx, website/src/pages/v1/index.mdx, website/src/pages/v2/index.mdx
Signed-off-by: Tuval Simha <tuval.simha@gmail.com>
=> Website docs: fix broken links - Error 404

packages/apollo-angular/CHANGELOG.md
=> Format ChangeLog for Changeset compatibility

.github/workflows/pr.yml, .github/workflows/release.yml
=> Setup `rc` releases and run ci for release PRs

.changeset/big-bears-roll.md
=> No changeset for demo

packages/apollo-angular/package.json
=> Declare our new node requirement

.changeset/big-bears-roll.md
=> Minor typo

website/next.config.js, website/src/pages/v1/index.mdx
=> Fix routes to 404

website/next.config.js
=> Added more paths to redirects

package.json, scripts/prepare-e2e.js, scripts/run-e2e-locally.sh
=> support angular 17 (Powerkiki forked)

yarn.lock
=> Revert JS update mess

website/src/pages/docs/data/mutations.mdx, website/theme.config.tsx
Because those are mostly either low quality questions/feedback or stale information.
=> Drop comments on website

.changeset/apollo-angular-2323-dependencies.md, .changeset/nice-singers-itch.md, .github/workflows/main.yml, packages/apollo-angular/package.json
=> Allow Angular 19

.changeset/fifty-lizards-applaud.md, packages/apollo-angular/src/query-ref.ts
=> `fetchMore` typing was too loose

.changeset/apollo-angular-2364-dependencies.md, .changeset/shaggy-rabbits-compare.md, .github/workflows/main.yml, packages/apollo-angular/package.json
=> Drop support for GraphQL 15
